---
defaultBaseImageVersion: latest
properties:
- name: API_KEY
  value: ${API_KEY}
  type: secure
- name: WORKSPACE_NAME
  value: ${WORKSPACE_NAME}
  type: text
stages:
- name: DEPLOY
  inputs:
  - type: git
    branch: master
    service: ${TERRAFORM_REPO}
  triggers:
  - type: commit
  jobs:
  - name: "Workspace Create"
    type: builder
    build_type: shell
    script: |
      #!/bin/bash
      echo "Workspace $WORKSPACE_ID"

      #force login again
      # calls to schematics were failing without it, 
      # so I *assume* that schematics only works if you're targeting some regions.
      # my toolchain was originally targeting us-east, but after forcing login to 
      # us-south, things started working.  this is fine for PoC, will have to be resolved
      # for a production template

      ibmcloud login --apikey $API_KEY -r us-south

      # test if schematics plugin is installed
      echo "attempting to locate schematics plugin..."
      if ! ibmcloud plugin list | grep schematics; then
        ibmcloud plugin install schematics -f
      fi
  



      # apply changes (there should actually be a terraform plan stage before this)
      ibmcloud terraform apply -i $WORKSPACE_ID --force




