---
defaultBaseImageVersion: latest
stages:
- name: DEPLOY
  inputs:
  - type: git
    branch: master
    service: ${TERRAFORM_REPO}
  triggers:
  - type: commit
  properties:
  - name: GITHUB_TOKEN
    value: undefined
    type: secure
  - name: WORKSPACE_NAME
    value: "undefined"
    type: text
  jobs:
  - name: "Workspace Create"
    type: deployer
    target:
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      echo "Workspace $WORKSPACE_NAME"

      # test if schematics plugin is installed
      echo "attempting to locate schematics plugin..."
      if ! ibmcloud plugin list | grep schematics; then
        ibmcloud plugin install schematics -f
      fi

      echo '{' \
        "    \"name\": \"$WORKSPACE_NAME\"," \
        '    "type": [' \
        '      "terraform-v1.0"' \
        '    ],' \
        '    "description": "the description",' \
        '    "tags": [],' \
        '    "template_repo": {' \
        '      "url": "https://github.com/triceam/cluster"' \
        '    },' \
        '    "template_data": [' \
        '      {' \
        '        "folder": ".",' \
        '        "type": "terraform-v1.0",' \
        '        "values": "",' \
        '        "variablestore": [' \
        '           {' \
        '               "name": "ibmcloud_api_key", ' \
        "               \"value\": \"$API_KEY\" " \
        '           }' \
        '       ]' \
        '      }' \
        '    ]' \
        '  }' > workspace-template.json
      
      ibmcloud terraform workspace new -f workspace-template.json -g $GITHUB_TOKEN
      
  - name: "Workspace Apply"
    type: deployer
    target:
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      echo "Workspace $WORKSPACE_NAME"

      # test if schematics plugin is installed
      echo "attempting to locate schematics plugin..."
      if ! ibmcloud plugin list | grep schematics; then
        ibmcloud plugin install schematics -f
      fi

      workspaces="$(ibmcloud terraform workspace list | grep "$WORKSPACE_NAME")"
      tokens=( $workspaces )
      workspace_id="${tokens[1]}"
      echo "Found: $workspace_id"

      ibmcloud terraform apply -i $workspace_id --force




